name: safespaceapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mvc_pattern: ^8.12.0
  shared_preferences: ^2.0.17
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  flutter_screenutil: ^5.0.0+2
  awesome_dialog: ^2.2.1
  url_launcher: ^6.1.8
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  dio: ^5.2.1+1
  google_sign_in: ^6.1.4
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/

  uses-material-design: true
  # Fonts ##########################################################################
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Alegreya-Bold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Alegreya-Medium.ttf


    - family: RegularAr
      fonts:
        - asset: assets/fonts/Alegreya-Regular.ttf

