name: safeSpace
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  mvc_pattern: ^8.12.0
  shared_preferences: ^2.0.17
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  flutter_screenutil: ^5.0.0+2
  awesome_dialog: ^2.2.1
  url_launcher: ^6.1.8
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  dio: ^5.2.1+1
  google_sign_in: ^6.1.4
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  just_audio: ^0.9.46
  audioplayers: ^6.2.0
  chat_gpt_sdk: ^3.1.4
  string_similarity: ^2.1.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  firebase_database: ^11.3.4
  translator: ^1.0.3+1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/

  uses-material-design: true
  # Fonts ##########################################################################
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Alegreya-Bold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Alegreya-Medium.ttf


    - family: RegularAr
      fonts:
        - asset: assets/fonts/Alegreya-Regular.ttf
